lang_name: "English"
title: "Kerosene, not for consumption"
description: "Questions about chemistry and chemistry programming projects, attempted by an undergrad majoring in chemistry."
date_format: "%b %-e, %Y"